### ISSUE TITLE
enhancement - repositories stargazed by a user

### ISSUE THREAD

**Issue by c-nv-s** [gennaro-tedesco/stargazer#10]
It could also be nice to be able to see stats on which repositories a user has starred themselves ( i.e. github.com/username?tab=stars )
and provide the same statistics:

NAME | URL | MAIN LANG | STARS | FORKS etc

**Comment by gennaro-tedesco** [comment]
Yes, I remember looking into it, however I could not fetch such information from the GitHub API. At the moment the program is calling [this address](https://github.com/gennaro-tedesco/stargazer/blob/c2412f911054b6c07d2d84ff92d30715fdb8c24c/cmd/getters.go#L56) whose response does not contain the required info. Do you know of the right endpoint to call to retrieve it?

**Comment by c-nv-s** [comment]
Sorry I am not very knowledgable about the api. Just thought i would offer this as a suggestion because it is related to stargazing. The tool is still nice even without this feature.

**Comment by gennaro-tedesco** [comment]
I will look into it again these days, I am sure there _must_ be a way to fetch this information (I will have a deeper look into the GitHub documentation).

**Comment by gennaro-tedesco** [comment]
Commit fda160aa26bf8a93818e019d18fef1004b4568a2 should address this problem: see example below

![Screen-Recording-2021-05-07-at-1](https://user-images.githubusercontent.com/15387611/117536840-b6006d00-affd-11eb-9f59-50000931bf6b.gif)

I am now doing an all-round test and will release a new version with this and [this other](https://github.com/gennaro-tedesco/stargazer/issues/9) change later on.

**Comment by gennaro-tedesco** [comment]
This has been introduced in [this release](https://github.com/gennaro-tedesco/stargazer/releases/tag/v1.2.0). `go get github.com/gennaro-tedesco/stargazer` to use the new features.

**Comment by c-nv-s** [comment]
Awesome. Thanks!
